### ISSUE TITLE
Nodejs file upload support

### ISSUE THREAD

**Issue by benkaiser** [appwrite/sdk-for-node#18]
I've tried several methods to call upload file but all with no sucess.

I have a Uint8Array that I am trying to upload, I know the file mime type also, but it doesn't appear I can pass that in any way through the SDK.

My current code looks roughly like this:
```
// setup
const appwriteSdk = require('node-appwrite');
let appwriteClient = new appwriteSdk.Client();
appwriteClient.setEndpoint(process.env.APPWRITE_URL).setProject(process.env.APPWRITE_PROJECT_ID).setKey(process.env.APPWRITE_API_SECRET);
const appwriteStorage = new appwriteSdk.Storage(appwriteClient);

// try to upload file
let contents = new Uint8Array(8); // 8 empty bytes for the example here
appwriteStorage.createFile(Buffer.from(contents), ['*']);
```

This current code results in the API returning a 400 with:
```
No file sent
```

I'm guessing this has something to do with the mimetype and filename not being set for the file field of the body. It starts roughly as follows:

```
----------------------------237413076769890169368363.
Content-Disposition: form-data; name="file".
Content-Type: application/octet-stream.
```

Compared to a manual file upload done from the admin console:

```
------WebKitFormBoundarytM78TqdmJGw2uqNA
Content-Disposition: form-data; name="file"; filename="myfile.webm"
Content-Type: video/webm
```

What is the proper way to do this file upload? I think I'm going to have to resert to manually calling the REST api until this can be fixed in the SDK.

**Comment by benkaiser** [comment]
My final solution looked like this calling the API directly:

```javascript
async function sendFileAppStorage(fileToSend, videoId) {
  const endpoint = appwriteClient.endpoint;
  let headers = Object.assign(appwriteClient.headers, {});
  const form = new FormData();
  form.append('file', Buffer.from(fileToSend), { filename: videoId + '.mp3', contentType: 'audio/mpeg' });
  form.append('read[]', '*');
  form.append('write[]', '');
  headers = {
    ...headers,
    ...form.getHeaders()
  };
  console.log(headers);
  await axios.post(endpoint + '/storage/files', form, {
    method: 'POST',
    params: {},
    headers: headers,
    responseType: 'json'
  });
}
```

**Comment by TorstenDittmann** [comment]
Yeah, as of right now we only support uploading a File/Readable Stream.

**Comment by Edijae** [comment]
@TorstenDittmann i'm receiving a file on my nodejs server using busboy. my attempt to save the stream ends up returning error with just status code of 400

```
const bb = busboy({headers:req.headers});
    bb.on('file', async (name,stream,info) =>{

        try {      
            let response = await api.getStorage().createFile(stream,[],[]);
            console.log("file upload response\n" +JSON.stringify(response));
        } catch (error) {
            console.log("failed to save file. "+error.stack); 
        }
        file.on('data', (data) => {
            console.log(`File [${name}] got ${data.length} bytes`);
          }).on('close', () => {
            console.log(`File [${name}] done`);
          });

    })

    bb.on('field', (name, val, info) => {
        console.log(`Field [${name}]: value: %j`, val);
      });

    bb.on('close', () => {
        console.log(`close called`);
        res.writeHead(200, { 'Connection': 'close' });
      });

      req.pipe(bb);
```

Error
```

Request failed with status code 400

Error: Request failed with status code 400

    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)

    at settle (/app/node_modules/axios/lib/core/settle.js:17:12)

    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:269:11)

    at IncomingMessage.emit (node:events:377:35)

    at endReadableNT (node:internal/streams/readable:1312:12)

    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by lohanidamodar** [comment]
Closing as no activity for long time. Feel free to reopen if the issue still exist.

**Comment by Edijae** [comment]
@lohanidamodar, @TorstenDittmann  I'm still not able to save the file as I receive it in the backend. I get the error below

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received an instance of FileStream

    at stat (node:fs:1108:10)

    at node:internal/util:335:7

    at new Promise (<anonymous>)

    at stat (node:internal/util:321:12)

    at Storage.createFile (/app/node_modules/node-appwrite/lib/services/storage.js:372:56)

    at Busboy.<anonymous> (file:///app/api/controllers/photoscontroller.js:36:51)

    at Busboy.emit (node:events:365:28)

    at Busboy.emit (/app/node_modules/busboy/lib/main.js:38:33)

    at PartStream.<anonymous> (/app/node_modules/busboy/lib/types/multipart.js:213:13)

    at PartStream.emit (node:events:365:28) {

  code: 'ERR_INVALID_ARG_TYPE'

}
```

implementation is as follows

```
const bb = busboy({headers:req.headers});
    bb.on('file', async (name,file,info) =>{

        try {
            console.log("name is "+name);
          
            let response = await api.getStorage().createFile(photoBucket,uniqueKey,file);
            console.log("file upload response -1 \n" +JSON.stringify(response));

        }catch(error){
            console.error(error);
        }

    })
```
