### ISSUE TITLE
🐛 Bug Report: AppwriteException response is mis classified as a string

### ISSUE THREAD

**Issue by codercatdev** [appwrite/sdk-for-node#44]
### 👟 Reproduction steps

Call method that returns an error. It will show the response as an object, but TS is typed as a string.

This will show
```
AppwriteException [Error]: A user with the same email already exists in your project.
    at Client.call (/Users/ajonp/web/dubstep-stack/node_modules/node-appwrite/lib/client.js:171:31)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Users.create (/Users/ajonp/web/dubstep-stack/node_modules/node-appwrite/lib/services/users.js:86:16)
    at createUser (/Users/ajonp/web/dubstep-stack/app/models/user.server.ts:10:16)
    at action5 (/Users/ajonp/web/dubstep-stack/app/routes/join.tsx:73:7)
    at Object.callRouteAction (/Users/ajonp/web/dubstep-stack/node_modules/@remix-run/server-runtime/dist/data.js:40:14)
    at handleDataRequest (/Users/ajonp/web/dubstep-stack/node_modules/@remix-run/server-runtime/dist/server.js:94:18)
    at requestHandler (/Users/ajonp/web/dubstep-stack/node_modules/@remix-run/server-runtime/dist/server.js:34:18)
    at /Users/ajonp/web/dubstep-stack/node_modules/@remix-run/express/dist/server.js:39:22 {
  code: 409,
  type: 'user_already_exists',
  response: {
    message: 'A user with the same email already exists in your project.',
    code: 409,
    type: 'user_already_exists',
    version: '1.0.1'
  }
}
```

### 👍 Expected behavior

https://github.com/appwrite/sdk-for-node/blob/6caaeb8253657df63377fb3aefcaff496f6108ae/index.d.ts#L1781

TS should change from 

```
  export class AppwriteException extends Error {
    public code: number | null;
    public response: string | null;
    constructor(message: string, code?: number, response?: string);
  }
  ```
  to
  ```
  export class AppwriteException extends Error {
    public code: number | null;
    public response: AppwriteExceptionResponse | null;
    constructor(message: string, code?: number, response?: string);
  }
    export type AppwriteExceptionResponse = {
      message:  string,
      code: number,
      type: string,
      version: number
    }
  }
  ```

### 👎 Actual Behavior

```
catch (error) {
    let message = 'Unknown Error'
    if (error instanceof AppwriteException) message = error?.response != null ? error.response : message;
    return json<ActionData>(
      { errors: { email: `${message} for ${email}` } },
      { status: 400 }
    );
  }
```

Causes `[object Object]`

### 🎲 Appwrite version

Version 0.10.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

No

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by codercatdev** [comment]
Resolved by https://github.com/appwrite/sdk-generator/issues/532
